spring.application.name=ch09-cassandra-chat-memory

#Logger Setting
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

#OpenAI API KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}

#Embedding Setting
spring.ai.openai.embedding.model=text-embedding-ada-002

#Cassandra
spring.cassandra.contact-points=localhost
spring.cassandra.port=9042
spring.cassandra.username=cassandra
spring.cassandra.password=1234
spring.cassandra.local-datacenter=datacenter1


#Chat Memory
spring.ai.chat.memory.repository.cassandra.initialize-schema=true
spring.ai.chat.memory.repository.cassandra.keyspace=spring_ai
spring.ai.chat.memory.repository.cassandra.table=chat_memory
spring.ai.chat.memory.repository.cassandra.time-to-live=60s











