spring.application.name=ch02

# OpenAI API KEY 설정
spring.ai.openai.api-key=${OPENAI_API_KEY}

# 정적 콘텐츠 캐시 설정
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.must-revalidate=true

# Thymeleaf 캐시 설정
spring.thymeleaf.cache=true