spring.application.name=ch08

#JDBC Setting
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=1234

#PGVector Setting
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.schema-name=public
spring.ai.vectorstore.pgvector.table-name=vector_store
spring.ai.vectorstore.pgvector.dimensions=1536
spring.ai.vectorstore.pgvector.index-type=HNSW

#Embedding Setting
spring.ai.openai.embedding.model=text-embedding-ada-002

#Logger Setting
logging.level.org.springframwork.ai.chat.client.advisor=DEBUG

#OpenAI API KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}









