spring.application.name=ch12-mcp-sse-client

#Logging
logging.level.io.modelcontextprotocol=DEBUG
logging.level.org.springframework.ai=DEBUG

#OpenAI API KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}

#MCP Setting
spring.ai.mcp.client.sse.connections.server1.url=http://localhost:8081