spring.application.name=ch11

#Logger Setting
logging.level.org.springframework.ai.chat.client.advisor=DEBUG
logging.level.org.springframework.ai.tool=DEBUG

#OpenAI API KEY
spring.ai.openai.api-key=${OPENAI_API_KEY}

#Serpapi
serpapi.endpoint=https://serpapi.com/search
serpapi.apiKey=1234