spring.application.name=shopping_vector

# PostgreSQL 연결
spring.datasource.url=jdbc:postgresql://localhost:5432/shopping_ai
spring.datasource.username=postgres
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

# OpenAI
spring.ai.openai.api-key=${OPENAI_API_KEY}

# OpenAI 임베딩 모델
spring.ai.openai.embedding.model=text-embedding-3-small
spring.ai.openai.embedding.dimensions=1536

# PGVector
spring.ai.vectorstore.pgvector.initialize-schema=false
spring.ai.vectorstore.pgvector.table-name=shopping_vector_store
spring.ai.vectorstore.pgvector.schema-validation=true
spring.ai.vectorstore.pgvector.dimensions=1536

server.port=8080